### ISSUE TITLE
Is there any way to automatically turn off cheats when entering the game? I switch fw16.0.1

### ISSUE THREAD

**Issue by ngophiphuong** [proferabg/EdiZon-Overlay#19] opened 2023-10-04 07:47 UTC

**Comment by ngophiphuong** [comment] 2023-10-05 04:46
yes, is there any way to disable automatic cheat activation? I tried editing the file as instructed on the forums but it still doesn't work.

**Comment by proferabg** [comment] 2023-10-05 07:10
Edizon does not handle enabling or disabling cheats on game load. That config setting in atmosphere is there to turn off cheats from enabling automatically in atmospheres built in cheat service. This overlay is just for easy toggling of cheats. As this issue is not caused by the edizon overlay, I will be closing it.

**Closed by proferabg** 2023-10-05 07:10 UTC
