### ISSUE TITLE
Edizon overlay crash at start

### ISSUE THREAD

**Issue by secfault** [proferabg/EdiZon-Overlay#22] opened 2024-03-31 01:09 UTC
Here is a screen of the crash
![IMG_20240331_030405](https://github.com/proferabg/EdiZon-Overlay/assets/37829347/e0bc8cf3-f4b0-4463-a0bd-a52d3266a013)

**Comment by proferabg** [comment] 2024-03-31 14:08
I will look into this throughout the week. Please be patient and continue to check back here for me to announce a fix and AMS 18 support.

**Comment by josete2k** [comment] 2024-03-31 20:01
Working here 

AMS 1.7.0
FW 18.0.0

**Comment by beyondmeat** [comment] 2024-05-18 03:57
use [ultra-hand](https://github.com/ppkantorski/Ultrahand-Overlay) instead of tesla-menu

**Comment by proferabg** [comment] 2024-06-06 13:44
This is an issue with not using up to date Tesla Menu. Closing as this is not a bug but a user error.

**Closed by proferabg** 2024-06-06 13:44 UTC
